server:
  port: 8081

app:
  products:
    dms:
      enabled: true
      name: ДМС при ДТП
      description: Продукт мед. страхования при ДТП
      tariff:
        path: "/home/andrey/packages/insurance-platform/calculator/src/test/resources/DMS_pri_DTP_ver1_rev25.xls"
        show-empty-values-params: false
    zdc:
      enabled: true
      name: Защита дохода 2.0
      description: Продукт страхования дохода при инвестиционных рисках
      tariff:
        path: "/home/andrey/packages/insurance-platform/calculator/src/test/resources/Zasita_dohoda_2.0_ver1_rev61.xls"
        show-empty-values-params: false
  profiling:
    enable: true
    pointcuts:
      - ru.virtusystems.domain.contract.StandardPartnerContractService
      - ru.virtusystems.domain.product.zachitadohoda20.ZachitaDohoda20CalculationService
      - ru.virtusystems.calculator.ExcelTariffDescriptor
      - ru.virtusystems.platform.database.repository.adapter

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: none
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    default-property-inclusion: non_null


logging:
  level:
    ru.virtusystems.platform.conf.profiler.CustomPerformanceMonitorInterceptor: TRACE
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    liquibase: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE