plugins {
    id 'java'
    id "io.freefair.lombok" version "8.4"
}

group = 'ru.virtusystems'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

apply from: "${rootDir}/versions.gradle"

dependencies {
    implementation project(':domain')
    // Excel
    implementation "org.apache.poi:poi:${versions.apache_poi}"
    implementation "org.apache.poi:poi-ooxml:${versions.apache_poi}"

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}